Areas/Admin/Controllers/CatalogueSliderController.cs
using Microsoft.AspNetCore.Mvc;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Web.Areas.Admin.Controllers;
using Nop.Web.Framework.Mvc.Filters;
using Nop.Plugin.Widgets.CatalogueSlider.Domain;
using Nop.Plugin.Widgets.CatalogueSlider.Services;
using Nop.Services.Media;
using Nop.Web.Framework.Mvc;
using System;
using Nop.Services.Configuration;
using Nop.Services.Security;
using Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
using Nop.Core;
using System.Linq;
using Nop.Services.Stores;
using Nop.Core.Caching;
using System.Threading.Tasks;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework;
using Nop.Plugin.Widgets.CatalogueSlider.Models;
using Nop.Web.Areas.Admin.Factories;
using Nop.Plugin.Widgets.CatalogueSlider.Factories;
using System.Collections.Generic;
using Nop.Web.Areas.Admin.Models.Catalog;
using Nop.Services.Logging;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Core.Domain.Logging;
using Nop.Plugin.Widgets.CatalogueSlider.Infrastructure.Cache;
using Nop.Services.Catalog;
using Nop.Plugin.Widgets.CatalogueSlider.Helpers;
using Nop.Web.Framework.Infrastructure;
using System.Reflection;
using static Nop.Plugin.Widgets.CatalogueSlider.Models.SliderModel;
using Nop.Services.Customers;
using Nop.Web.Framework.Factories;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace Nop.Plugin.Widgets.CatalogueSlider.Controllers
{
    [AuthorizeAdmin]
    [Area(AreaNames.Admin)]
    [AutoValidateAntiforgeryToken]
    public class CatalogueSliderController : BasePluginController
    {
        #region Fields
        private readonly ISliderModelFactory _sliderModelFactory;
        private readonly ISliderService _sliderService;
        private readonly ISettingService _settingService;
        private readonly IStoreContext _storeContext;
        private readonly IPermissionService _permissionService;
        private readonly IBaseAdminModelFactory _baseAdminModelFactory;
        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly IPictureService _pictureService;
        private readonly ICustomerActivityService _customerActivityService;
        private readonly ILogger _logger;
        private readonly IStaticCacheManager _staticCacheManager;
        private readonly ICategoryService _categoryService;
        private readonly ICustomerService _customerService;
        private readonly IStoreService _storeService;
        private readonly IAclService _aclService;
        private readonly IStoreMappingService _storeMappingService;
        private readonly IAclSupportedModelFactory _aclSupportedModelFactory;
        private readonly IStoreMappingSupportedModelFactory _storeMappingSupportedModelFactory;
        #endregion

        #region Ctor

        public CatalogueSliderController(
            ISliderModelFactory sliderModelFactory,
            ISliderService sliderService, 
            ISettingService settingService,
            IStoreContext storeContext,
            IPermissionService permissionService,
            IBaseAdminModelFactory baseAdminModelFactory,
            ILocalizationService localizationService,
            INotificationService notificationService,
            IPictureService pictureService,
            ICustomerActivityService customerActivityService,
            ILogger logger,
            IStaticCacheManager staticCacheManager,
            ICategoryService categoryService,
            ICustomerService customerService,
            IStoreService storeService,
            IAclService aclService,
            IStoreMappingService storeMappingService,
            IAclSupportedModelFactory aclSupportedModelFactory,
            IStoreMappingSupportedModelFactory storeMappingSupportedModelFactory
            )
        {
            _sliderModelFactory = sliderModelFactory;
            _sliderService = sliderService;
            _settingService = settingService;
            _storeContext = storeContext;
            _permissionService = permissionService;
            _baseAdminModelFactory = baseAdminModelFactory;
            _localizationService = localizationService;
            _notificationService = notificationService;
            _pictureService = pictureService;
            _customerActivityService = customerActivityService;
            _logger = logger;
            _staticCacheManager = staticCacheManager;
            _categoryService = categoryService;
            _customerService = customerService;
            _storeService = storeService;
            _aclService = aclService;
            _storeMappingService = storeMappingService;
            _aclSupportedModelFactory = aclSupportedModelFactory;
            _storeMappingSupportedModelFactory = storeMappingSupportedModelFactory;
        }

        #endregion

        #region Utilities
        private IEnumerable<SelectListItem> GetWidgetFilterd(string[] filters)
        {
            //generate empty list
            var selectList = new List<SelectListItem>();
            //if (string.IsNullOrEmpty(filter)) return selectList;
            if (filters?.Length == 0) return selectList;
            foreach (string filter in filters)
            {
                CatalogEnum myEnum = (CatalogEnum)Enum.Parse(typeof(CatalogEnum), filter);
                var all = WidgetZoneHelper.GetCustomWidgetZoneSelectList().Where(w => w.Text.Contains(myEnum.ToString()));
                foreach (var s in all)
                {
                    //add elements in dropdown
                    selectList.Add(new SelectListItem
                    {
                        Value = s.Value.ToString(),
                        Text = s.Text.ToString()
                    });
                }
            }
            return selectList;
        }
        private IEnumerable<SelectListItem> GetCatalogFilterd(string[] filters)
        {
            IList<SelectListItem> selectList = new List<SelectListItem>();

            if (filters?.Length == 0) return selectList;
            foreach (string f in filters)
            {
                //var enumDisplayStatus = (CatalogEnum)filter;
                //CatalogEnum myEnum = (CatalogEnum)filter;

                CatalogEnum myEnum = (CatalogEnum)Enum.Parse(typeof(CatalogEnum), f);
                string filter = myEnum.ToString();
                try
                {
                    if (filter[0].ToString().ToLower() == "c")
                    {
                        //((List<SelectListItem>)selectList).AddRange(_sliderModelFactory.GetSelectCategory().Result);
                        var list = _sliderModelFactory.GetSelectCategory().Result;
                        foreach (var s in list)
                        {
                            //add elements in dropdown
                            selectList.Add(new SelectListItem
                            {
                                Value = "c-" + s.Value.ToString(),
                                Text = s.Text.ToString()
                            });
                        }
                    }
                    else if (filter[0].ToString().ToLower() == "m")
                    {
                        //((List<SelectListItem>)selectList).AddRange(_sliderModelFactory.GetSelectManufacture().Result);
                        var list = _sliderModelFactory.GetSelectManufacture().Result;
                        foreach (var s in list)
                        {
                            //add elements in dropdown
                            selectList.Add(new SelectListItem
                            {
                                Value = "m-" + s.Value.ToString(),
                                Text = s.Text.ToString()
                            });
                        }
                    }
                    else
                    {
                        //((List<SelectListItem>)selectList).AddRange(_sliderModelFactory.GetSelectVendor().Result);
                        var list = _sliderModelFactory.GetSelectVendor().Result;
                        foreach (var s in list)
                        {
                            selectList.Add(new SelectListItem
                            {
                                Value = "v-" + s.Value.ToString(),
                                Text = s.Text.ToString()
                            });
                        }
                    }
                }
                catch (Exception)
                {

                }
            }
            
            return selectList;
        }
        protected async Task SaveSliderAclAsync(Slider slider, SliderModel model)
        {
            slider.SubjectToAcl = model.SelectedCustomerRoleIds.Any(); 
            await _sliderService.UpdateSliderAsync(slider);

            var existingAclRecords = await _aclService.GetAclRecordsAsync(slider);
            var allCustomerRoles = await _customerService.GetAllCustomerRolesAsync(true);
            foreach (var customerRole in allCustomerRoles)
            {
                if (model.SelectedCustomerRoleIds.Contains(customerRole.Id))
                {
                    //new role
                    if (existingAclRecords.Count(acl => acl.CustomerRoleId == customerRole.Id) == 0)
                        await _aclService.InsertAclRecordAsync(slider, customerRole.Id);
                }
                else
                {
                    //remove role
                    var aclRecordToDelete = existingAclRecords.FirstOrDefault(acl => acl.CustomerRoleId == customerRole.Id);
                    if (aclRecordToDelete != null)
                        await _aclService.DeleteAclRecordAsync(aclRecordToDelete);
                }
            }
        }
        protected async Task SaveStoreMappingsAsync(Slider slider, SliderModel model)
        {
            slider.LimitedToStores = model.SelectedStoreIds.Any();

Areas/Admin/Views/CatalogueSlider/Configure.cshtml
@model ConfigurationModel

@{
    ViewBag.PageTitle = T("Plugins.Widgets.CatalogueSlider.Configuration").Text;
    Html.SetActiveMenuItemSystemName("CatalogueSliderSettings");
}

<form asp-controller="CatalogueSlider" asp-action="Configure" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Plugins.Widgets.CatalogueSlider.Configuration")
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
        </div>
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="form-horizontal">
                @*@await Component.InvokeAsync("StoreScopeConfiguration")*@
                <div asp-validation-summary="All"></div>
                <div class="cards-group">
                    <div class="card card-default">
                        <div class="card-body">
                            <div class="form-group row">
                                <div class="col-md-3">
                                    @*<nop-override-store-checkbox asp-for="EnableSlider_OverrideForStore" asp-input="EnableSlider" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />*@
                                    <nop-label asp-for="EnableSlider" />
                                </div>
                                <div class="col-md-9">
                                    <nop-editor asp-for="EnableSlider" />
                                </div>
                            </div>
                            @*<div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="SelectedWidgetZonesIds" />
                                </div>
                                <div class="col-md-9">
                                    <nop-select asp-for="SelectedWidgetZonesIds" asp-items="Model.AllWidgetZones" asp-multiple="true" />
                                </div>
                            </div>


                            <script type="text/javascript">
                                $(document).ready(function () {
                                    var savedZones = $('#@Html.IdFor(model => model.SelectedWidgetZonesIds)').data("kendoMultiSelect");
                                    savedZones.setOptions({
                                    autoClose: false,
                                    filter: "contains"
                                });

                                @if (Model.AllWidgetZones.Count == 0)
                                {
                                    <text>
                                    savedZones.setOptions({
                                        enable: false,
                                        placeholder: '@T("No Field Available Right Now")'
                                    });
                                    savedZones._placeholder();
                                    savedZones._enable();
                                    </text>
                                }
                            });
                            </script>*@

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</form>

Areas/Admin/Views/CatalogueSlider/Create.cshtml
@model SliderModel
@inject AdminAreaSettings adminAreaSettings
@{
    //page title
    ViewBag.PageTitle = T("Plugins.Widgets.CatalogueSlider.AddNew").Text;
    //active menu item (system name)
    //Html.SetActiveMenuItemSystemName("CatalogueSlider");
    Html.SetActiveMenuItemSystemName("CatalogueSlider");
}

<form asp-controller="CatalogueSlider" asp-action="Create" method="post" id="catalogue-slider-form">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Plugins.Widgets.CatalogueSlider.AddNew")
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Plugins.Widgets.CatalogueSlider.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
        </div>
    </div>


    @await Html.PartialAsync("~/Plugins/Widgets.CatalogueSlider/Areas/Admin/Views/CatalogueSlider/_CreateOrUpdate.cshtml", Model)
</form>

Areas/Admin/Views/CatalogueSlider/Edit.cshtml
@model SliderModel

@{
    //page title
    ViewBag.PageTitle = T("Plugins.Widgets.CatalogueSlider.EditDetails").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("CatalogueSlider");
}

<form asp-controller="CatalogueSlider" asp-action="Edit" method="post" id="catalogue-slider-form">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Plugins.Widgets.CatalogueSlider.EditDetails")
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Plugins.Widgets.CatalogueSlider.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @*<button type="button" id="slider-delete" class="btn btn-danger">
                <i class="far fa-trash-alt"></i>
                @T("Admin.Common.Delete")
            </button>*@
        </div>
    </div>
    @await Html.PartialAsync("~/Plugins/Widgets.CatalogueSlider/Areas/Admin/Views/CatalogueSlider/_CreateOrUpdate.cshtml", Model)
</form>

<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="slider-delete" asp-action="Delete" />

Areas/Admin/Views/CatalogueSlider/SliderItemCreatePopup.cshtml
@model SliderItemModel

@{ Layout = "_AdminPopupLayout";

    //page title
    ViewBag.PageTitle = T("Plugins.Widgets.CatalogueSlider.SliderItem.AddNewItem").Text; }

    <form asp-controller="CatalogueSlider" asp-action="SliderItemCreate"
        asp-route-btnId="@Context.Request.Query["btnId"]"
        asp-route-formId="@Context.Request.Query["formId"]">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Plugins.Widgets.CatalogueSlider.SliderItem.AddNewItem")
        </h1>
        <div class="float-right">
            @*<button type="button" id="addItemPicture" class="btn btn-primary">@T("Admin.Common.Save")</button>*@
            <button type="submit" name="save" class="btn btn-primary">@T("Admin.Common.Save")</button>
        </div>
    </div>

    <div class="content">
        <div class="form-horizontal">
            @await Html.PartialAsync("~/Plugins/Widgets.CatalogueSlider/Areas/Admin/Views/CatalogueSlider/_PictureUpload.cshtml", Model)
        </div>
    </div>
    </form>





    @*<form asp-controller="CatalogueSlider" asp-action="ProductAttributeValueCreatePopup"
              asp-route-productAttributeMappingId="@Context.Request.Query["productAttributeMappingId"]"
              asp-route-btnId="@Context.Request.Query["btnId"]"
              asp-route-formId="@Context.Request.Query["formId"]">
            <div class="content-header clearfix">
                <h1 class="float-left">
                    @T("Admin.Catalog.Products.ProductAttributes.Attributes.Values.AddNew")
                </h1>
                <div class="float-right">
                    <button type="submit" name="save" class="btn btn-primary">
                        <i class="far fa-save"></i>
                        @T("Admin.Common.Save")
                    </button>
                </div>
            </div>
            @await Html.PartialAsync("_CreateOrUpdateProductAttributeValue", Model)
        </form>*@

Areas/Admin/Views/CatalogueSlider/SliderItemEditPopup.cshtml
@model SliderItemModel

@{ Layout = "_AdminPopupLayout";

    //page title
    ViewBag.PageTitle = T("Plugins.Widgets.CatalogueSlider.SliderItem.EditItem").Text; }

    <form asp-controller="CatalogueSlider" asp-action="SliderItemEdit"
        asp-route-btnId="@Context.Request.Query["btnId"]"
        asp-route-formId="@Context.Request.Query["formId"]">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Plugins.Widgets.CatalogueSlider.SliderItem.EditItem")
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">@T("Admin.Common.Save")</button>
        </div>
    </div>

    <div class="content">
        <div class="form-horizontal">
            @await Html.PartialAsync("~/Plugins/Widgets.CatalogueSlider/Areas/Admin/Views/CatalogueSlider/_PictureUpload.cshtml", Model)
        </div>
    </div>
    </form>





    @*<form asp-controller="CatalogueSlider" asp-action="ProductAttributeValueCreatePopup"
              asp-route-productAttributeMappingId="@Context.Request.Query["productAttributeMappingId"]"
              asp-route-btnId="@Context.Request.Query["btnId"]"
              asp-route-formId="@Context.Request.Query["formId"]">
            <div class="content-header clearfix">
                <h1 class="float-left">
                    @T("Admin.Catalog.Products.ProductAttributes.Attributes.Values.AddNew")
                </h1>
                <div class="float-right">
                    <button type="submit" name="save" class="btn btn-primary">
                        <i class="far fa-save"></i>
                        @T("Admin.Common.Save")
                    </button>
                </div>
            </div>
            @await Html.PartialAsync("_CreateOrUpdateProductAttributeValue", Model)
        </form>*@

Areas/Admin/Views/CatalogueSlider/_CreateOrUpdate.Info.cshtml
@model SliderModel
@inject IJsonHelper Json
@Html.HiddenFor(x => x.EntityStringIds)
@Html.HiddenFor(x => x.Id)
<div class="card-body">
    <div class="form-group row">
        <div class="col-md-3">
            <nop-label asp-for="Name" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="Name" asp-required="true" />
            <span asp-validation-for="Name"></span>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-3">
            <nop-label asp-for="CatalogTypeIds" />
        </div>
        <div class="col-md-9">
            <nop-select asp-for="CatalogTypeIds" asp-items="@Model.CatalogTypeList" asp-multiple="true" />

        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-3">
            <nop-label asp-for="@Model.EntityIds" />
        </div>
        <div class="col-md-9">
            <nop-select asp-for="EntityIds" asp-items="Model.CategoryList" asp-multiple="true" />
        </div>
    </div>
    <span asp-validation-for="EntityIds"></span>
    <div class="form-group row">
        <div class="col-md-3">
            <nop-label asp-for="@Model.WidgetZoneIds" />
        </div>
        <div class="col-md-9">
            <nop-select asp-for="WidgetZoneIds" asp-items="Model.WidgetZoneItems" asp-multiple="true" />
        </div>
    </div>
    <span asp-validation-for="WidgetZoneIds"></span>

    <script asp-location="Footer">
        let editablepage = $('#@Html.IdFor(model => model.Id)').val() > 0 ? true : false;
        $(document).ready(function () {
            var saveCatalogType = $('#@Html.IdFor(model => model.CatalogTypeIds)').data("kendoMultiSelect");
            saveCatalogType.setOptions({
                autoClose: false,
                filter: "contains"
            });

            //if (editablepage) {
                var selected = [];
                $('#@Html.IdFor(model => model.CatalogTypeIds) :selected').each(function () {
                    selected.push($(this).val());
                });
            console.log(selected);
            editablepage = selected.length > 0 ? true : false;
            if (editablepage) {
                catalogChange(selected);
                @*let catText = $('#@Html.IdFor(model => model.CatalogTypeIds) option:selected').val();
                console.log(catText);*@

            }
            $('#@Html.IdFor(model => model.CatalogTypeIds)').change(function (e) {
                let selected = $(e.target).val();
                //console.dir(selected);
                catalogChange(selected);
            });

            $('#@Html.IdFor(model => model.EntityIds)').change(function (e) {
                var data = [];
                var $el = $('#@Html.IdFor(model => model.EntityIds)');
                $el.find('option:selected').each(function () {
                    //data.push({ value: $(this).val() });
                    data.push( $(this).val());
                });
                //console.log(data);
                //console.log(data.join(','));
                $('#@Html.IdFor(model => model.EntityStringIds)').val(data.join(','));
            });

        });

                //$('body').on('DOMSubtreeModified', '#CatalogTypeIds_taglist', function () {
                //    console.log($('#CatalogTypeIds_taglist').html());
                //});



        var firstTime = true;
         function catalogChange(catText) {
             if (catText != null) {
                 if (firstTime) {
                     getWidgetZoneFilter(catText);
                     getCatalogs(catText);
                     $.when(getWidgetZoneFilter(catText)).then(function (response, textStatus, jqXHR) {
                         getCatalogs(catText);
                     });
                     firstTime = false;
                 }
                 else {
                     getCatalogs(catText); getWidgetZoneFilter(catText);
                 }
             }
        }
        function getCatalogs(catText) {
        var postData = {
            'filters': catText
        };
        var url = "@Url.Action("GetCatalogs", "CatalogueSlider", new { Area = "Admin" })";
        $.ajax({
            cache: false,
            type: "GET",
            traditional: true,
            url: url,
            data: postData,
            contentType: "application/json",
            dataType: "json",
            success: successFunc,
            error: errorFunc
        });

            function successFunc(data) {
               let select = $('#@Html.IdFor(model => model.EntityIds)');
                select.empty();
                let entityStringIds = [];

                $.each(data, function (index, itemData) {
                    select.append($('<option/>', {
                        'value': itemData.Value,
                        'text': itemData.Text
                    }));
                });
                multiselectEntityId(data)
            }
        }

        function getWidgetZoneFilter(catText) {
            var url = "@Url.Action("GetWidgetWithFilter", "CatalogueSlider", new { Area = "Admin" })";

            var postData = { 'filters': catText };
            $.ajax({
                cache: false,
                type: "GET",
                //contentType: 'application/json; charset=utf-8',
                traditional: true,
                data: postData,
                url: url,
                datatype: JSON,
                //data: JSON.stringify(postData),
                success: successWidgetFunc,
                error: errorFunc
            });

            function successWidgetFunc(data) {
                let select = $('#@Html.IdFor(model => model.WidgetZoneIds)');
                select.empty();
                //let h = '';
                $.each(data, function (index, itemData) {
                    select.append($('<option/>', {
                        value: itemData.Value,
                        text: itemData.Text
                    }));
                });
                multiselectWidgetId(data);
            }


        }
        function errorFunc() {
            // alert('error');
        }
        function multiselectEntityId(d) {
             var savedEntityIds = $('#@Html.IdFor(model => model.EntityIds)').data("kendoMultiSelect");
                            savedEntityIds.setOptions({
                                autoClose: false,
                                filter: "contains"
                            });
                let obj = {};
            obj.catalog = [];
            if (editablepage) {
                    let entityString = $('#@Html.IdFor(model => model.EntityStringIds)').val();
                    entityStringIds = entityString.split(',');
            }

            $.each(d, function (key, value) {
                obj.catalog.push({ "text": value.Text, "value": value.Value });

            });
            savedEntityIds.setDataSource(obj);

            if (editablepage) {
                savedEntityIds.value(entityStringIds);
                //if (jQuery.inArray(value.Value, entityStringIds) !== -1) {
                //}
            }

            savedEntityIds.refresh();
            }

    function multiselectWidgetId(d) {
        var savedWidgetZone = $('#@Html.IdFor(model => model.WidgetZoneIds)').data("kendoMultiSelect");
                                            savedWidgetZone.setOptions({
                                            autoClose: false,
                                            filter: "contains"
                                            });
        let obj = {};
        obj.widget = [];
        $.each(d, function (key, value) {
            obj.widget.push({ "text": value.Text, "value": value.Value });
        });
        savedWidgetZone.setDataSource(obj);



        if (editablepage) {
             let widgetZoneIds = @Json.Serialize(Model.WidgetZoneIds);
                let w = [];
                for (var i = 0; i < widgetZoneIds.length; i++) {
                    w.push(widgetZoneIds[i].toString());
            }
            savedWidgetZone.value(w);
        }
        savedWidgetZone.refresh();
    }
    </script>

    <div class="form-group row">
        <div class="col-md-3">
            <nop-label asp-for="@Model.TimeInterval" />
        </div>
        <div class="col-md-6">
            <nop-editor asp-for="TimeInterval" />
        </div>
        <div class="col-md-3">

        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-3">
            <nop-label asp-for="@Model.IsActive" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="IsActive" />
            <span asp-validation-for="IsActive"></span>
        </div>
    </div>
    <div class="form-group row @(Model.StartTime.HasValue ? "advanced-setting" : null)">
        <div class="col-md-3">
            <nop-label asp-for="StartTime" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="StartTime" />
            <span asp-validation-for="StartTime"></span>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-3">
            <nop-label asp-for="EndTime" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="EndTime" />
            <span asp-validation-for="EndTime"></span>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-3">
            <nop-label asp-for="SelectedCustomerRoleIds" />
        </div>
        <div class="col-md-9">
            <nop-select asp-for="SelectedCustomerRoleIds" asp-items="@Model.AvailableCustomerRoles" asp-multiple="true" />
            <script type="text/javascript">
                    $(document).ready(function () {
                        var saveUserRole = $('#@Html.IdFor(model => model.SelectedCustomerRoleIds)').data("kendoMultiSelect");
                        saveUserRole.setOptions({
                            autoClose: false,
                            filter: "contains"
                        });
                    });
            </script>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-3">
            <nop-label asp-for="SelectedStoreIds" />
        </div>
        <div class="col-md-9">
            <nop-select asp-for="SelectedStoreIds" asp-items="@Model.AvailableStores" asp-multiple="true" />
            <script type="text/javascript">
                    $(document).ready(function () {
                        var saveStore = $('#@Html.IdFor(model => model.SelectedStoreIds)').data("kendoMultiSelect");
                        saveStore.setOptions({
                            autoClose: false,
                            filter: "contains"
                        });
                    });
            </script>
        </div>
    </div>
</div>
@*<div class="col-md-9 offset-md-3">
        <button type="submit" id="btnAddNewValue" onclick="javascript:OpenWindow('@(Url.Action("SliderEntityPopup", "Product", new { productAttributeMappingId = Model.Id, btnId = "btnRefresh", formId = "productattribute-form" }))', 800, 750, true);return false;" class="btn btn-primary">
            @T("Admin.Catalog.Products.ProductAttributes.Attributes.Values.AddNew")
        </button>
    </div>*@